Table user_auth_table {
  userid string pk
  username string unique
  password string 
  private_key string
  publish_key string
  level number
  TimeToExist number
}

Table device_credential_table {
  deviceid string pk
  device_private string
  userid string
  name string
  meshid string
  meshpass string
}
Ref: device_credential_table.userid > user_auth_table.userid

Table device_data_table {
  time timestamp
  deviceid string
  data string
}
Ref: device_data_table.deviceid - device_credential_table.deviceid

Table device_scene_table {
  id string pk
  deviceid string
  data string
  exp number
}
Ref: device_scene_table.deviceid - device_credential_table.deviceid
